### ISSUE TITLE
Add a Contact entity CRUD

### ISSUE THREAD

**Issue by davidromani** [Flexible-User-Experience/pas-a-repas#10]
Create a CRUD for Contact entity with this tutorial http://symfony.com/doc/master/bundles/SensioGeneratorBundle/commands/generate_doctrine_crud.html

Tip: use annotation format
Bonus: try to disable the create, edit & delete functions

**Comment by aserratorta** [comment]
is it ok?

**Comment by davidromani** [comment]
it depends... did you discovered the new routes that has been added? there is a misconfiguration inside  the new views... check which files has been added after the CRUD command execution (it will helps)

finally we must to secure this (admin) area.
