### ISSUE TITLE
read only database

### ISSUE THREAD

**Issue by aserratorta** [Flexible-User-Experience/pas-a-repas#12]
Hi,
this is the error when a try to fill the contact form in homepage. It looks like my contact table was read only...

![image](https://cloud.githubusercontent.com/assets/12971681/11611245/258d3a08-9bc4-11e5-9cbe-5ff473dd239f.png)

**Comment by aserratorta** [comment]
Is it maybe because I created The CRUD controller?

**Comment by davidromani** [comment]
Probably... check app/database/data.db3 file permissions and tray to fix it.
