### ISSUE TITLE
Admin global improvements

### ISSUE THREAD

**Issue by davidromani** [Flexible-User-Experience/pas-a-repas#17]
We need to apply some refactors to the admin section (backend). First of all we need to create a dedicated layout for the admin section. Finally we need an admin/dasboard view.

Resume:
· create a new backend layout (all the /admin/... views must extend from this one)
· add a top menu only with links to main CRUD views (index) and a "back to frontend" link
· remove footer section from backend layout
· add an admin/dashboard screen as a main backend entry-point with useful information

**Comment by aserratorta** [comment]
I don't understand this issue.
Do I have to create a CRUD called Dashboard?

**Comment by davidromani** [comment]
No, a "dashboard" is just the entry-point view to the backend area. Usually in a dashboard we show a welcome message and a list of all the entity names (with a link to each index view) that we could manage inside the securized area.
