### ISSUE TITLE
Use datetimepicker widget

### ISSUE THREAD

**Issue by davidromani** [Flexible-User-Experience/pas-a-repas#21]
To improve the user experience dealing with dates and times follow this tutotial https://github.com/stephanecollot/DatetimepickerBundle and use it on admin forms

**Comment by davidromani** [comment]
![captura de pantalla 2015-12-13 a la s 11 21 53](https://cloud.githubusercontent.com/assets/698779/11766523/1f1c2af8-a18c-11e5-828a-e516427edb8f.png)

**Comment by davidromani** [comment]
Replace the Stephan bundle by this one https://github.com/genemu/GenemuFormBundle

Use this section: https://github.com/genemu/GenemuFormBundle/blob/master/Resources/doc/jquery/datepicker/index.md

**Comment by aserratorta** [comment]
However I installed The Intl Component keeps showing me this error:


![sense nom2](https://cloud.githubusercontent.com/assets/12971681/11889992/b18d17be-a54f-11e5-98db-54a2b4e9c121.png)
