### ISSUE TITLE
Fix selectivity translation message

### ISSUE THREAD

**Issue by davidromani** [Flexible-User-Experience/pas-a-repas#22]
I think that this part needs to be showed more clearly (like a bullets list)
![captura de pantalla 2015-12-13 a la s 11 37 21](https://cloud.githubusercontent.com/assets/698779/11766571/7f7a3e24-a18e-11e5-9fbc-6761b5977574.png)

**Comment by aserratorta** [comment]
I decided justify all the courses text :stuck_out_tongue:
