### ISSUE TITLE
Show latest messages

### ISSUE THREAD

**Issue by davidromani** [Flexible-User-Experience/pas-a-repas#23]
Show latest contact messages amount in dashboard admin view. Take care only about messages sent during current week.

**Comment by davidromani** [comment]
Use a Bootstrap badge to display the number (http://getbootstrap.com/components/#badges)

**Comment by aserratorta** [comment]
The bootstrap gryd has a dust :tired_face:

**Comment by davidromani** [comment]
try to improve how to display the amount counters with http://getbootstrap.com/components/#panels
