### ISSUE TITLE
Update Java 8

### ISSUE THREAD

**Issue by davidromani** [Flexible-User-Experience/pas-a-repas#32]
Recently, I've discovered that latest OSX version downgrade Java to v1.6. This has a negative impact on PhpStorm performance and memory consumption, so check which version do you have with this command:

```
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

If you have 1.6 version (instead 1.8) then you must install this http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by aserratorta** [comment]
Done it!
![image](https://cloud.githubusercontent.com/assets/12971681/12076305/32489cc2-b1a6-11e5-97e1-514066e57199.png)
