### ISSUE TITLE
MonthGroup Admin

### ISSUE THREAD

**Issue by aserratorta** [Flexible-User-Experience/pas-a-repas#36]
I was trying to create the MonthGroup Admin but it showed me this error:
![image](https://cloud.githubusercontent.com/assets/12971681/12213992/f6c0d730-b684-11e5-9d44-5f0bb046a2fa.png)

**Comment by davidromani** [comment]
You have some namespace mess, check carefull relation between file name, location and namespace

**Comment by aserratorta** [comment]
Oh my god! It was a silly thing! :grin:
:+1:
