### ISSUE TITLE
receipt.date = unique

### ISSUE THREAD

**Issue by aserratorta** [Flexible-User-Experience/pas-a-repas#39]

**Comment by aserratorta** [comment]
receipt.date = assert (unique)

**Comment by aserratorta** [comment]
$type -> enums (grouphourprice / singlehourprice

**Comment by aserratorta** [comment]
Have a look at this code. It blows up as it could expect! 
Can't i make unique DateTrait.date, can I?

**Comment by davidromani** [comment]
Search for same example in pas-a-repas project, I think that there is some entities with unique titles.

If you apply on Trait every entity that uses this trait will be date unique, and we don't need this strategy. We need that only receipt date will be unique. Think about it.
