### ISSUE TITLE
<span class="label {% if object.type == 'HOUR_GROUP' %}...

### ISSUE THREAD

**Issue by aserratorta** [Flexible-User-Experience/pas-a-repas#42]
If I apply this code, 
![image](https://cloud.githubusercontent.com/assets/12971681/12526531/92101eb4-c16e-11e5-87b9-827607f60a27.png)
look what happens with the view:
![image](https://cloud.githubusercontent.com/assets/12971681/12526596/4fe10a84-c16f-11e5-8e6b-1bfc92104ff8.png)

**Comment by davidromani** [comment]
this is because you are not applying an enough logical strategy... hint:
```
if (something)
 draw full html span node for hour_group type
else
 draw full html span node for hour_single type
endif
```
