### ISSUE TITLE
Add blog views

### ISSUE THREAD

**Issue by davidromani** [Flexible-User-Experience/pas-a-repas#5]
Create new blog views to display the objects loaded before with the controller:

Posts list view. Every post will show:
· published date
· thumbnail image
· title
· short description
· related categories list
· a link to detail view

Post detail view:
· published date
· full size image
· title
· full description
· related categories list (every category has a link to its detail view)

Categories list view. Every category will show:
· title
· how many related posts contains

Category detail view:
· title
· related posts list (every post has a link to its detail view)

**Comment by aserratorta** [comment]
Let me the weekend :sweat:
