### ISSUE TITLE
Improve email validation

### ISSUE THREAD

**Issue by davidromani** [Flexible-User-Experience/pas-a-repas#6]
We need to be more strong & strict with the email form field validation. To solve this issue, we need to apply an email validator to Contact entity.

So follow these steps:

· add "use Symfony\Component\Validator\Constraints as Assert;" in src/AppBundle/Entity/Contact.php
· add "@Assert\Email()" annotation to email field
· set "strict", "checkMX" & "checkHost" options equal to "true" (http://gitnacho.github.io/symfony-docs-es/book/validation.html)
· test contact form against wrong emails

Be careful, "strict" option requires this vendor library https://packagist.org/packages/egulias/email-validator

**Comment by davidromani** [comment]
Again too much fast :-P Your are setting different option values, read my issue slowly

**Comment by aserratorta** [comment]
I changed you told it to me, but it isn't working very well...
