### ISSUE TITLE
Show human dates

### ISSUE THREAD

**Issue by davidromani** [Flexible-User-Experience/pas-a-repas#7]
Congratulations! Your posts list view looks pretty amazing, well done!!

But we are humans not robots, so please apply "day/month/year" format to the published date attribute. And we don't need to take care about the timestamp too.

**Comment by aserratorta** [comment]
Thanks!

**Comment by davidromani** [comment]
Not so fast friend and read issue carefully... apply "d/m/Y" format not "Y-m-d"

**Comment by aserratorta** [comment]
Better now? :grin:
